Traceback (most recent call last):
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
np.roots([-9.81/2*np.ones(50), np.sqrt(2*Pat_W/0.15)*np.sin(Pat_angle), 1])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [11][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mnp[49m[38;5;241;43m.[39;49m[43mroots[49m[43m([49m[43m[[49m[38;5;241;43m-[39;49m[38;5;241;43m9.81[39;49m[38;5;241;43m/[39;49m[38;5;241;43m2[39;49m[38;5;241;43m*[39;49m[43mnp[49m[38;5;241;43m.[39;49m[43mones[49m[43m([49m[38;5;241;43m50[39;49m[43m)[49m[43m,[49m[43m [49m[43mnp[49m[38;5;241;43m.[39;49m[43msqrt[49m[43m([49m[38;5;241;43m2[39;49m[38;5;241;43m*[39;49m[43mPat_W[49m[38;5;241;43m/[39;49m[38;5;241;43m0.15[39;49m[43m)[49m[38;5;241;43m*[39;49m[43mnp[49m[38;5;241;43m.[39;49m[43msin[49m[43m([49m[43mPat_angle[49m[43m)[49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m][49m[43m)[49m

File [0;32m<__array_function__ internals>:5[0m, in [0;36mroots[0;34m(*args, **kwargs)[0m

File [0;32m~/.conda/envs/newwork/lib/python3.9/site-packages/numpy/lib/polynomial.py:234[0m, in [0;36mroots[0;34m(p)[0m
[1;32m    231[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mInput must be a rank-1 array.[39m[38;5;124m"[39m)
[1;32m    233[0m [38;5;66;03m# find non-zero array entries[39;00m
[0;32m--> 234[0m non_zero [38;5;241m=[39m [43mNX[49m[38;5;241;43m.[39;49m[43mnonzero[49m[43m([49m[43mNX[49m[38;5;241;43m.[39;49m[43mravel[49m[43m([49m[43mp[49m[43m)[49m[43m)[49m[[38;5;241m0[39m]
[1;32m    236[0m [38;5;66;03m# Return an empty array if polynomial is all zeros[39;00m
[1;32m    237[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(non_zero) [38;5;241m==[39m [38;5;241m0[39m:

File [0;32m<__array_function__ internals>:5[0m, in [0;36mnonzero[0;34m(*args, **kwargs)[0m

File [0;32m~/.conda/envs/newwork/lib/python3.9/site-packages/numpy/core/fromnumeric.py:1921[0m, in [0;36mnonzero[0;34m(a)[0m
[1;32m   1829[0m [38;5;129m@array_function_dispatch[39m(_nonzero_dispatcher)
[1;32m   1830[0m [38;5;28;01mdef[39;00m [38;5;21mnonzero[39m(a):
[1;32m   1831[0m     [38;5;124;03m"""[39;00m
[1;32m   1832[0m [38;5;124;03m    Return the indices of the elements that are non-zero.[39;00m
[1;32m   1833[0m 
[0;32m   (...)[0m
[1;32m   1919[0m 
[1;32m   1920[0m [38;5;124;03m    """[39;00m
[0;32m-> 1921[0m     [38;5;28;01mreturn[39;00m [43m_wrapfunc[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mnonzero[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/.conda/envs/newwork/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57[0m, in [0;36m_wrapfunc[0;34m(obj, method, *args, **kwds)[0m
[1;32m     54[0m     [38;5;28;01mreturn[39;00m _wrapit(obj, method, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m     56[0m [38;5;28;01mtry[39;00m:
[0;32m---> 57[0m     [38;5;28;01mreturn[39;00m [43mbound[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m     58[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m     59[0m     [38;5;66;03m# A TypeError occurs if the object does have such a method in its[39;00m
[1;32m     60[0m     [38;5;66;03m# class, but its signature is not identical to that of NumPy's. This[39;00m
[0;32m   (...)[0m
[1;32m     64[0m     [38;5;66;03m# Call _wrapit from within the except clause to ensure a potential[39;00m
[1;32m     65[0m     [38;5;66;03m# exception has a traceback chain.[39;00m
[1;32m     66[0m     [38;5;28;01mreturn[39;00m _wrapit(obj, method, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

[0;31mValueError[0m: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

